name: test
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  ci-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest, windows-latest, ubuntu-latest ]
        go: [ 1.21, 1.22, 1.23 ]
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
      - name: Set up golang with version ${{ matrix.go }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
      - name: Run tests
        run: go test -v -coverprofile=covprofile ./...
      - name: Send coverage
        if: ${{ matrix.os == 'macos-latest' && matrix.go == '1.14'}}
        uses: shogo82148/actions-goveralls@v1.4.2
        with:
          path-to-profile: covprofile